version: "3"
services:
  html:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes: 
      - C:\CreatioDemo\site.conf:/etc/nginx/conf.d/site.conf
      - C:\CreatioDemo\EventTrackingCreatio:/code
    links:
      - php
    
  php:
    image: php:7-fpm
    volumes: 
      - C:\CreatioDemo\EventTrackingCreatio:/code